
# Install nginx and make sure that it is running
---
- hosts: local
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify: start nginx
  handlers:
    - name: start nginx
      systemd:
        name: nginx
        state: started